export const REGISTER = 'REGISTER';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const MAKE_APPOINTMENT = 'ADD_APPOINTMENT';
export const CANCEL_APPOINTMENT = 'DELETE_APPOINTMENT';